### ISSUE TITLE
error when printing

### ISSUE THREAD

**Issue by elukaweski** [postcasio/atom-printer#3]
just trying to do a print on a file ( packages -> printer -> print) and get an error, as follows...BTW..thanks for anyhelp :) Edwin

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [printer](https://github.com/postcasio/atom-printer) package, v0.0.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/elukaweski/Documents/mac/ZipTemp/github/atom-printer/lib/printer.coffee:58

TypeError: undefined is not a function
    at Object.module.exports.AtomPrinter.getEditorHTML (/Users/elukaweski/Documents/mac/ZipTemp/github/atom-printer/lib/printer.coffee:62:25)
    at Object.module.exports.AtomPrinter.print (/Users/elukaweski/Documents/mac/ZipTemp/github/atom-printer/lib/printer.coffee:45:29)
    at atom-workspace.subscriptions.add.atom.commands.add.printer:print (/Users/elukaweski/Documents/mac/ZipTemp/github/atom-printer/lib/printer.coffee:17:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

### Commands

```
     -0:00.5.0 printer:print (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
pretty-json, v0.3.3
printer, v0.0.0
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by grinsted** [comment]
I have the same issue.

**Comment by grinsted** [comment]
I could not make a proper fix, but i made a small ugly hack that atleast allows me to print (but now without highlighting). Here's the code if anybody stumbles here and wants quick fix. Modify getEditorHTML in printer.coffee thus:
```coffee
  getEditorHTML: ->
    editor = atom.workspace.getActiveTextEditor()
    html = editor.getText()
    console.log html
    html
```

**Comment by palant** [comment]
This issue is being resolved by https://github.com/postcasio/atom-printer/pull/4.
